apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: legacy
  legacySortOptions:
    orderFirst:
    - Namespace
    - ResourceQuota
    - StorageClass
    - CustomResourceDefinition
    - MutatingWebhookConfiguration
    - ServiceAccount
    - PodSecurityPolicy
    - NetworkPolicy
    - Role
    - ClusterRole
    - RoleBinding
    - ClusterRoleBinding
    - ConfigMap
    - Secret
    - Endpoints
    - Service
    - LimitRange
    - PriorityClass
    - PersistentVolume
    - PersistentVolumeClaim
    - Deployment
    - StatefulSet
    - CronJob
    - PodDisruptionBudget
    orderLast:
    - ValidatingWebhookConfiguration

resources:
# Cert-Manager
#- ../common/cert-manager/base
- ../common/cert-manager/kubeflow-issuer/base
# Istio
- ../common/istio/istio-crds/base
- ../common/istio/istio-namespace/base
- ../common/istio/istio-install/overlays/oauth2-proxy
# NOTE: For Google Kubernetes Engine (GKE), use:
# - ../common/istio/istio-install/overlays/gke
#GKE mounts `/opt/cni/bin` as read-only for security reasons, preventing the Istio CNI installer from writing the CNI binary.
#Use the GKE-specific overlay: `kubectl apply -k common/istio/istio-install/overlays/gke`.
#This overlay uses GKE's writable CNI directory at `/home/kubernetes/bin`.
#For more details, see [Istio CNI Prerequisites](https://istio.io/latest/docs/setup/additional-setup/cni/#prerequisites) and [Platform Prerequisites](https://istio.io/latest/docs/ambient/install/platform-prerequisites/)
# oauth2-proxy
# NOTE: only uncomment ONE of the following overlays, depending on your cluster type
- ../common/oauth2-proxy/overlays/m2m-dex-only     # for all clusters
#- ../common/oauth2-proxy/overlays/m2m-dex-and-kind # for KIND clusters (allows K8S JWTs for gateway auth)
#- ../common/oauth2-proxy/overlays/m2m-dex-and-eks  # for EKS clusters (NOTE: requires you to configure issuer, see overlay)
# Dex
- ../common/dex/overlays/oauth2-proxy
# KNative
- ../common/knative/knative-serving/overlays/gateways
# Uncomment the following line if `knative-eventing` is required
# - ../common/knative/knative-eventing/base
- ../common/istio/cluster-local-gateway/base
# Kubeflow namespace
- ../common/kubeflow-namespace/base
# NetworkPolicies
- ../common/networkpolicies/base
# Kubeflow Roles
- ../common/kubeflow-roles/base
# Kubeflow Istio Resources
- ../common/istio/kubeflow-istio-resources/base
# TODO: Uncomment the following line after the next KFP release
# - ../applications/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user  # Pipeline definitions stored in the database
# Kubeflow Pipelines (SeaweedFS default)
- ../experimental/seaweedfs/istio
# - ../applications/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user-k8s-native # Pipeline Definitions Stored as Kubernetes Resources
# Katib
- ../applications/katib/upstream/installs/katib-with-kubeflow
# Central Dashboard
- ../applications/centraldashboard/overlays/oauth2-proxy
# Admission Webhook
- ../applications/admission-webhook/upstream/overlays/cert-manager
# Jupyter Web App
- ../applications/jupyter/jupyter-web-app/upstream/overlays/istio
# Notebook Controller
- ../applications/jupyter/notebook-controller/upstream/overlays/kubeflow
# Profiles + KFAM with PSS (Pod Security Standards)
- ../applications/profiles/pss # TODO MUST BE UPSTREAMED
# PVC Viewer
- ../applications/pvcviewer-controller/upstream/base
# Volumes Web App
- ../applications/volumes-web-app/upstream/overlays/istio
# Tensorboards Controller
- ../applications/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
# Tensorboard Web App
- ../applications/tensorboard/tensorboards-web-app/upstream/overlays/istio
# Training Operator (v1)
# - ../applications/training-operator/upstream/overlays/kubeflow
# Trainer (Training Operator v2)
- ../applications/trainer/overlays
# User namespace
- ../common/user-namespace/base
# KServe
- ../applications/kserve/kserve
- ../applications/kserve/models-web-app/overlays/kubeflow
# Spark Operator
- ../applications/spark/spark-operator/overlays/kubeflow

# Ray is an experimental integration
# Here is the documentation for Ray: https://docs.ray.io/en/latest/
# Here is the internal documentation for Ray: - ../experimental/ray/README.md
# - ../experimental/ray/kuberay-operator/overlays/kubeflow

# Newly created resources
- resources/kubeflow-trainer-cert.yaml

patches:
- path: patches/istiod-webhook-hostnetwork.yaml
- path: patches/knative-webhook-hostnetwork.yaml
- path: patches/kserve-webhook-hostnetwork.yaml
- path: patches/kubeflow-trainer-webhook-hostnetwork.yaml
- path: patches/istio-cni-config.yaml
- target:
    kind: Deployment
    name: net-istio-webhook
    namespace: knative-serving
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/ports
      value: 
        - name: metrics
          containerPort: 19090
        - name: profiling
          containerPort: 18008
        - name: https-webhook
          containerPort: 18443
    - op: add
      path: /spec/template/spec/hostNetwork
      value: true
    - op: add
      path: /spec/template/spec/dnsPolicy
      value: ClusterFirstWithHostNet
    - op: replace
      path: /spec/template/spec/containers/0/env/5/value
      value: "18443"
    - op: replace
      path: /spec/template/spec/containers/0/readinessProbe/httpGet/port
      value: 18443
    - op: replace
      path: /spec/template/spec/containers/0/livenessProbe/httpGet/port
      value: 18443
- target:
    kind: Deployment
    name: kserve-controller-manager
    namespace: kubeflow
  patch: |-
    - op: add
      path: /spec/template/spec/hostNetwork
      value: true
    - op: add
      path: /spec/template/spec/dnsPolicy
      value: ClusterFirstWithHostNet
    - op: replace
      path: /spec/template/spec/containers/0/args/0
      value: --metrics-addr=127.0.0.1:28080
    - op: replace
      path: /spec/template/spec/containers/0/readinessProbe/httpGet/port
      value: 28081
    - op: replace
      path: /spec/template/spec/containers/0/livenessProbe/httpGet/port
      value: 28081
    - op: replace
      path: /spec/template/spec/containers/0/ports/0
      value:
        containerPort: 29443
        name: webhook-server
        protocol: TCP
        hostPort: 29443
    - op: replace
      path: /spec/template/spec/containers/1/args/0
      value: --secure-listen-address=0.0.0.0:28443
    - op: replace
      path: /spec/template/spec/containers/1/args/1
      value: --upstream=http://127.0.0.1:28080/
    - op: replace
      path: /spec/template/spec/containers/1/ports/0
      value:
        containerPort: 28443
        name: https
        protocol: TCP
        hostPort: 28443


components:
# https://kubernetes.io/docs/concepts/security/pod-security-standards/
# For all static namespaces we already enforce PSS restricted
# This should be used together with Kubernetes 1.33+ user namespaces to block root user exploits
- ../common/security/PSS/dynamic/baseline
