apiVersion: apps/v1
kind: Deployment
metadata:
  name: kserve-controller-manager
  namespace: kubeflow
spec:
  template:
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      