apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflow-trainer-controller-manager
  namespace: kubeflow-system
spec:
  template:
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
