apiVersion: v1
kind: Namespace
metadata:
  name: kubeflow-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflow-trainer-controller-manager
  namespace: kubeflow-system
spec:
  template:
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: kubeflow-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubeflow-trainer-webhook-cert
  namespace: kubeflow-system
spec:
  dnsNames:
  - kubeflow-trainer-controller-manager.kubeflow-system.svc
  - kubeflow-trainer-controller-manager.kubeflow-system.svc.cluster.pakcarik
issuerRef:
  name: selfsigned-issuer
  kind: Issuer