# Step 1: Root CA Issuer
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: kubeflow-system
spec:
  selfSigned: {}

---
# Step 2: Root CA Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubeflow-root-ca
  namespace: kubeflow-system
spec:
  isCA: true
  commonName: kubeflow-root-ca
  secretName: kubeflow-root-ca
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer

---
# Step 3: CA Issuer (uses the CA above)
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kubeflow-ca-issuer
  namespace: kubeflow-system
spec:
  ca:
    secretName: kubeflow-root-ca

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: kubeflow-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubeflow-trainer-webhook-cert
  namespace: kubeflow-system
spec:
  secretName: kubeflow-trainer-webhook-cert
  dnsNames:
  - kubeflow-trainer-controller-manager.kubeflow-system.svc
  - kubeflow-trainer-controller-manager.kubeflow-system.svc.cluster.pakcarik
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer